info:
  model: int-scaffold
packages:
- gitBranch: release/1.0.0
  gitServerName: rahulsiv
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  name: CriticalProject
- gitServerName: rahulsiv
  gitTag: v1.0.0
  gitUrl: https://github.com/johnpcarter
  gitUsername: Rahul-Sivakumar-IBM
  name: JcHelloWorldAPI
  version: '1.0'
services:
- packages:
  - name: CriticalProject
    version: 1.0.0
  - name: JcHelloWorldAPI
    version: '1.0'
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmRegistry: licensed
    wpmServer: https://packages.webmethods.io
  serviceName: project.critical.integrations:DAF1
- packages:
  - name: WmPublic
    version: 12.1.0.0.1202
  serviceName: pub.date:calculateDateDifference
- packages:
  - name: CriticalProject
    version: 1.0.0
  - name: JcHelloWorldAPI
    version: '1.0'
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmRegistry: licensed
    wpmServer: https://packages.webmethods.io
  serviceName: project.critical.referencedata:ref
version: 1.0.0
