version: "1.0"
info:
  model: int-scaffold
packages:
- name: CriticalProject
  gitServerName: rahulsiv
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  gitBranch: main
- name: JcHelloWorldAPI
  gitServerName: rahulsiv
  gitUrl: https://github.com/johnpcarter
  gitUsername: Rahul-Sivakumar-IBM
  gitTag: v1.0.0
